---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/23 0023 下午 9:34
---
local m = {};
--require("bgfx_lua");
local func_wrap = require("func_wrap");
local func_gs = require("func_to_getset");

local function dumpInit(init_wrapper, out)
    out.type = init_wrapper.type();
    out.vendorId = init_wrapper.vendorId();
    out.deviceId = init_wrapper.deviceId();
    out.debug = init_wrapper.debug();
    out.profile = init_wrapper.profile();
    out.platformData = init_wrapper.platformData();
    out.resolution = init_wrapper.resolution();
    out.limits = init_wrapper.limits();
    return out;
end

function m.getInit()
    local init = bgfx_lua.getInit();
    return func_gs.wrapUserdata(init);
end

function m.newApp(func_pre_init, func_init, func_draw, func_destroy)
    return bgfx_lua.newApp(
            func_wrap.wrapEasy(func_pre_init, "app_pre_init"),
            func_wrap.wrapEasy(func_init, "app_init"),
            func_wrap.wrapEasy(func_draw, "app_draw"),
            func_wrap.wrapEasy(func_destroy, "app_destroy")
    );
end

function m.setDebug(debugFlags)
    return bgfx_lua.setDebug(debugFlags);
end

---
--- setViewClear
---  _id: the view id
--- c_flags: clear flags
--- c_rgba: clear rgba
--- c_depth: clear depth
--- c_stencil: clear stencil
function m.setViewClear(_id, c_flags, c_rgba, c_depth, c_stencil)
    print("bgfx >>> setViewClear")
    bgfx_lua.setViewClear(_id, c_flags, c_rgba, c_depth, c_stencil);
end

function m.setViewRect(_id, x, y, w, h)
    print("bgfx >>> setViewRect")
    bgfx_lua.setViewRect(_id, x, y, w, h);
end

function m.touch(id)
    print("bgfx >>> touch")
    bgfx_lua.touch(id);
end

function m.dbgTextClear()
    print("bgfx >>> dbgTextClear")
    bgfx_lua.dbgTextClear();
end

--- image: const char *
function m.dbgTextImage(x, y, w, h,image, pitch)
    print("bgfx >>> dbgTextImage")
    bgfx_lua.dbgTextImage(x, y, w, h,image, pitch);
end

function m.dbgTextPrintf(x, y, attrib, format,...)
    local a = {...};
    local str = string.format(format, table.unpack(a));
    print("bgfx >>> dbgTextPrintf, str =", str)
    bgfx_lua.dbgTextPrintf(x, y , attrib, str);
end

function m.frame(capture)
    print("bgfx >>> frame")
    bgfx_lua.frame(capture);
end

function m.getStats()
    print("bgfx >>> getStats")
    return func_gs.wrapUserdataGet(bgfx_lua.getStats());
end
--- new VertexLayout.
--- @return VertexLayout from bgfx pkg
function m.newVertexLayout()
    return bgfx_lua.newVertexLayout();
end

---
---@return userdata of Memory
function m.makeRef(ud_mem)
    return bgfx_lua.makeRef(ud_mem);
end
--- create vertex buffer
--- @param mem_ref: the memory ref return from 'makeRef(ud_mem)'.
--- @param verLayout_ref: vertex layout ref
--- @param flags: the flags. default is 0
--- @return vertexBufferHandle
function m.createVertexBuffer(mem_ref, verLayout_ref, flags)
    if(not flags) then
        flags = 0;
    end
    return bgfx_lua.createVertexBuffer(mem_ref, verLayout_ref, flags);
    end
--- create vertex buffer
--- @param mem_ref: the memory ref return from 'makeRef(ud_mem)'.
--- @param verLayout_ref:
--- @param flags: the flags . default is 0
--- @return IndexBufferHandle
function m.createIndexBuffer(mem_ref, flags)
    if not flags then
        flags = 0;
    end
    return bgfx_lua.createIndexBuffer(mem_ref, flags);
end

---
--- createProgram
--- @param v_sh: ShaderHandle of vertex
--- @param f_sh: ShaderHandle of fragment
--- @param destroy_shader: true if destroy shader
--- @return ProgramHandle
function m.createProgram(v_sh, f_sh, destroy_shader)
    return bgfx_lua.createProgram(v_sh, f_sh, destroy_shader);
end
---
--- createProgram
--- @param v_sh: name of vertex shader
--- @param f_sh: name of fragment shader
--- @return ProgramHandle
function m.loadProgram(v_sh_name, f_sh_name)
    return bgfx_lua.loadProgram(v_sh_name, f_sh_name);
end
return m;