---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/27 0027 下午 10:15
---
local m = {};
local bx1 = require("bx_lua");

function m.getHPCounter()
    return bx1.getHPCounter();
end

function m.getHPFrequency()
    return bx1.getHPFrequency();
end

return m;