---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/23 0023 下午 3:20
---
local mo = {};
local fn_id = 0

local function generate_func_id ()
    fn_id = fn_id + 1
    return fn_id
end

local function del_callback(name)
    _G[name] = nil;
end

local function create_callback_table (fn, name)
    local t = {}
    t.callback = fn
    setmetatable (t, {__call =  -- 关注__call
                      function (tab, ...) -- 在t(xx)时，将调用到这个函数
                          tab.callback (...) -- 真正的回调
                          if(name) then
                              del_callback (name);  -- 回调完毕，清除wrap建立的数据
                          end
                      end })
    return t
end

function mo.wrap (fn)
    local id = generate_func_id() -- 产生唯一的id
    local fn_s = "_callback_fn"..id
    _G[fn_s] = create_callback_table(fn, fn_s) -- _G[fn_s]对应的是一个表
    return fn_s
end

function mo.wrapEasy(fn, name)
    _G[name] = create_callback_table(fn, nil);
    return name;
end

return mo;