---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/24 0024 上午 10:38
---

local m = {};

--- wrap user data: for native
function m.wrapUserdata(u)
    if(type(u) == 'userdata') then
        local self = {};
        -- get and set
        local meta = {
            __index = function(t, k)
                print(u, "__index, k =", k);
                return m.wrapUserdata(u.call(u, tostring(k), nil));
            end,
            __newindex = function(t, k, v)
                print(u, "__newindex, k =", k);
                return m.wrapUserdata(u.call(u, tostring(k), v));
            end,
            __tostring = function(t)
                return "wrapper: "..tostring(u);
            end
        };
        setmetatable(self, meta);
        return self;
    else
        --print("only used for user data");
        return u;
    end
end

return m;