---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/8/28 0028 上午 10:03
---

local m = {};
local mem = require("hmem_lua");

--- create memory. type: can be 'd', 'w', 'b', 'f'.
--- 'd' is u-int32
--- 'w' is u-int16
--- 'b' is u-int8
--- 'f' is float
--- ...: means multi array. or just a int for the length of memory.
--- params: (type, table...) or (type, len)
function m.new(type, ...)
    return mem.new(type, ...);
end

--- create fix type memory: 'float-float-float-uint32'
--- ...: means multi table of 'fffui'.
function m.newFFFUI(...)
    -- lua 'table.unpack()' as parameter must be the final parameter.or else the lua stack only contains first parameter.
    return mem.new('fffd',...);
end

--- create memory matrix .
--- @param ...: can be (tables) or (rowCount, columnCount)
function m.newMat(type, ...)
    return mem.newMat(type, ...);
end

--- load file to memory
function m.loadFile(filepath)
    return mem.loadFile(filepath);
end

--- load asset file to memory
function m.loadFileFromAssets(path)
    return mem.loadFileFromAssets(path);
end

return m;