---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/10/26 0026 下午 6:14
---
local mem = require("hmem_lua")
print("mem.computeTypes", mem);
local function assertB(c1, c2)
    print(c1, c2);
    assert(c1 == c2);
end

-- f,d,w,b, i, s, c, F
print("base: ", 'b')
assertB(mem.test_comp('b', 'b') ,'b');
assertB(mem.test_comp('b', 'w') , 'w');
assertB(mem.test_comp('b', 'd'), 'd');
assertB(mem.test_comp('b', 'f') , 'f');

assertB(mem.test_comp('b', 'c'), 'c');--todo
assertB(mem.test_comp('b', 's') , 's');
assertB(mem.test_comp('b', 'i') , 'i');
assertB(mem.test_comp('b', 'F') , 'F');