---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/11 0011 下午 3:13
---
local mem = require("memory")

local me = mem.new("fdwbiscF", {1.1,2,3,4,5,6,7,8.88}, {11,12,13,14,15,16,17,18})
print("me = ", me)