---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/3 0003 上午 10:55
---
local uiCore = require("fr.UiCore")

function sinf(val)
    return math.sin(val);
end
function cosf(val)
    return math.cos(val);
end
function nvgRGBA(r, g, b, a)
    return uiCore.newColorRgba(r, g, b, a);
end
function nvgRadialGradient(cx, cy, inr, outr, icol, ocol)
    return uiCore.newRadialGradient(cx, cy, inr, outr, icol, ocol)
end