---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 下午 6:28
---
local as = require("fr.AppStarter")
local view = require("fr.View")
local uiCore = require("fr.UiCore")
local bx = require("bx")
local bgfx = require("bgfx")
local math2 = require("core.utils.Math")

local function sinf(val)
    return math.sin(val);
end
local function cosf(val)
    return math.cos(val);
end
local function nvgRGBA(r, g, b, a)
    return uiCore.newColorRgba(r, g, b, a);
end
local function nvgRadialGradient(cx, cy, inr, outr, icol, ocol)
    return uiCore.newRadialGradient(cx, cy, inr, outr, icol, ocol)
end

local function newRectViewTester()
    local self = view.new("LineViewTester")

    function self.onInitialize(ctx)
    end

    function self.onDestroy()
    end

    function self.onDraw(canvas)
        print("---newTestView: onDraw ----")
        --canvas_lua.h_testDraw(canvas.getContext());
        self.testBezier_strokeColor(canvas);

        canvas.offsetPosition(0, 300)
        self.testBezier_fillColor(canvas);

        canvas.setPosition(0, 0)
    end

    function self.testBezier_strokeColor(canvas)
        canvas.beginPath()
              .moveTo(50, 100)
              .quadTo(50, 50, 100, 50)
              .moveTo(200, 200)
              .bezierTo(200, 250, 250, 250, 280, 180)
              .strokeColor(nvgRGBA(255,0,0,255))
              .stroke();
    end

    function self.testBezier_fillColor(canvas)
        canvas.beginPath()
              .moveTo(50, 100)
              .quadTo(50, 50, 100, 50)
              .moveTo(200, 200)
              .bezierTo(200, 250, 250, 250, 280, 180)
              .fillColor(nvgRGBA(255,0,0,255))
              .fill();
    end

    return self;
end
as.startViews(nil, newRectViewTester())