---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 下午 6:28
---
local as = require("fr.AppStarter")
local view = require("fr.View")
local uiCore = require("fr.UiCore")
local bx = require("bx")
local bgfx = require("bgfx")

require("tests.fr.BaseTest")


local function newRectViewTester()
    local self = view.new("LineViewTester")

    function self.onInitialize(ctx)
    end

    function self.onDestroy()
    end

    function self.onDraw(canvas)
        print("---newTestView: onDraw ----")
        --canvas_lua.h_testDraw(canvas.getContext());
        self.testLine_fillColor(canvas);
        canvas.offsetPosition(0, 60)
        self.testLine_StrokeColor(canvas);
        canvas.offsetPosition(0, 60)
        self.testLine_fillGradient(canvas);
        canvas.offsetPosition(0, 60)
        self.testLine_strokeGradient(canvas);
        canvas.setPosition(0, 0)
    end

    function self.testLine_fillColor(canvas)
        canvas.beginPath()
              .moveTo(50, 50)
              .lineTo(100, 50)
               .lineTo(100, 100)
               .lineTo(50, 100)
                .lineTo(50, 50)
              .fillColor(nvgRGBA(255,192,0,255))
              .fill();
    end
    function self.testLine_StrokeColor(canvas)
        canvas.beginPath()
              .moveTo(50, 50)
              .lineTo(100, 50)
              .lineTo(100, 100)
              .lineTo(50, 100)
                .lineTo(50, 50)
              .strokeWidth(3)
              .strokeColor(nvgRGBA(255,192,0,255))
              .stroke();
    end

    function self.testLine_fillGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 100;
        local y2 = 100;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
                .moveTo(50, 50)
                .lineTo(100, 50)
                .lineTo(100, 100)
                .lineTo(50, 100)
                .lineTo(50, 50)
              .fillGradient(bg)
              .fill();
    end

    function self.testLine_strokeGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 100;
        local y2 = 100;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
              .moveTo(50, 50)
              .lineTo(100, 50)
              .lineTo(100, 100)
              .lineTo(50, 100)
               .lineTo(50, 50)
              .strokeGradient(bg)
              .stroke();
    end

    return self;
end
as.startViews(nil, newRectViewTester())