---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 下午 6:28
---
local as = require("fr.AppStarter")
local view = require("fr.View")
local uiCore = require("fr.UiCore")
local bx = require("bx")
local bgfx = require("bgfx")

require("tests.fr.BaseTest")

local function newRectViewTester()
    local self = view.new("RectViewTester")

    function self.onInitialize(ctx)
    end

    function self.onDestroy()
    end

    function self.onDraw(canvas)
        print("---newTestView: onDraw ----")
        --canvas_lua.h_testDraw(canvas.getContext());

        canvas.setPosition(0, 0)
        self.testRoundRect_fillColor(canvas);
        canvas.offsetPosition(0, 50);
        self.testRoundRect_fillGradient(canvas);
        canvas.offsetPosition(0, 50);
        self.testRoundRect_strokeColor(canvas);
        canvas.offsetPosition(0, 50);
        self.testRoundRect_strokeGradient(canvas)

        canvas.offsetPosition(0, 50);
        self.testRect_fillColor(canvas);
        canvas.offsetPosition(0, 50);
        self.testRect_fillGradient(canvas);
        canvas.offsetPosition(0, 50);
        self.testRect_strokeColor(canvas);
        canvas.offsetPosition(0, 50);
        self.testRect_strokeGradient(canvas)
    end

    function self.testRoundRect_fillColor(canvas)
        canvas.beginPath()
              .roundedRect(50, 50, 300, 30, 10)
              .fillColor(nvgRGBA(255,192,0,255))
              .fill();
    end
    function self.testRoundRect_strokeColor(canvas)
        canvas.beginPath()
              .roundedRect(50, 50, 300,30, 10)
              .strokeWidth(3)
              .strokeColor(nvgRGBA(255,192,0,255))
              .stroke();
    end
    function self.testRoundRect_fillGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 50 + 300;
        local y2 = 50 + 30;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
              .roundedRect(50, 50, 300, 30, 10)
              .fillGradient(bg)
              .fill();
    end
    function self.testRoundRect_strokeGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 50 + 300;
        local y2 = 50 + 30;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
              .roundedRect(50, 50, 300, 30, 10)
              .strokeGradient(bg)
              .stroke();
    end

    function self.testRect_fillColor(canvas)
        canvas.beginPath()
              .rect(50, 50, 300, 30)
              .fillColor(nvgRGBA(255,192,0,255))
              .fill();
    end
    function self.testRect_strokeColor(canvas)
        canvas.beginPath()
              .rect(50, 50, 300,30)
              .strokeWidth(3)
              .strokeColor(nvgRGBA(255,192,0,255))
              .stroke();
    end
    function self.testRect_fillGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 50 + 300;
        local y2 = 50 + 30;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
              .rect(50, 50, 300, 30)
              .fillGradient(bg)
              .fill();
    end
    function self.testRect_strokeGradient(canvas)
        local x1 = 50;
        local y1 = 50;
        local x2 = 50 + 300;
        local y2 = 50 + 30;
        local bg = uiCore.newLinearGradient(x1, y1, x2, y2, nvgRGBA(0, 160, 192, 0),
                nvgRGBA(0, 160, 192, 64))
        canvas.beginPath()
              .rect(50, 50, 300, 30)
              .strokeGradient(bg)
              .stroke();
    end

    return self;
end
as.startViews(nil, newRectViewTester())