---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 下午 6:28
---
local as = require("fr.AppStarter")
local view = require("fr.View")
local uiCore = require("fr.UiCore")
local bx = require("bx")
local bgfx = require("bgfx")
local math2 = require("core.utils.Math")

require("tests.fr.BaseTest")

local function newRectViewTester()
    local self = view.new("LineViewTester")
    local ts1;

    function self.onInitialize(ctx)
        ts1 = uiCore.newTextStyle();
        ts1.font(uiCore.newFontFromAssets(ctx, "sans-bold", "runtime/font/roboto-bold.ttf"))
        .size(18)
        --.lineHeight()
        --.blur(2)
        --.letterSpace(5)
        .color(nvgRGBA(255,192,0,255))
       -- .hAlign(uiCore.TEXT_ALIGN_Center)
         .vAlign(uiCore.TEXT_ALIGN_Top) -- baseline may cause can't see in '(0, 0)'
    end

    function self.onDestroy()
    end

    function self.onDraw(canvas)
        print("---newTestView: onDraw ----")
        --canvas_lua.h_testDraw(canvas.getContext());
        self.testText_strokeColor(canvas);

       -- canvas.offsetPosition(0, 300)
        --self.testBezier_fillColor(canvas);

        --canvas.setPosition(0, 0)
    end

    function self.testText_strokeColor(canvas)
        canvas.beginPath()
              .textStyle(ts1)
              .fillText("Hello world!", 100, 100);

        canvas.beginPath()
              .textStyle(ts1)
              .fillText("Hello world!", 0 , 0);

        canvas.beginPath()
              .textStyle(ts1)
              .fillText("Hello world!", 0 , 300);

        canvas.beginPath()
              .textStyle(ts1)
              .fillText("Hello world!", 50 , 0);

        canvas.beginPath()
              .textStyle(ts1)
              .fillText("Hello world!", 50, 200);
        local w, h = canvas.measureText("Hello world!", 0, 0);
        print("wh: ",w, h)
    end

    return self;
end
as.startViews(nil, newRectViewTester())