---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/10 0010 下午 5:29
---

local obj = require("core.Object")
local m = {}
--todo 多个形状

function m.rectsFill(rects, c)
    local self = obj.new("RectFillDrawable")
    function self.draw(canvas)
        canvas.beginPath();
        for _, rc in ipairs(rects) do
            canvas.rect(rc.x, rc.y, rc.w, rc.h);
        end
        canvas.fillColor(c)
              .fill();
    end
    return self;
end
function m.rectFill(x, y, w, h, c)
    local self = obj.new("RectFillDrawable")
    function self.draw(canvas)
        canvas.beginPath()
              .rect(x, y, w, h)
              .fillColor(c)
              .fill();
    end
    return self;
end

function m.rectsStroke(rects, c, strokeW)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath();
        for _, rc in ipairs(rects) do
            canvas.rect(rc.x, rc.y, rc.w, rc.h);
        end
        canvas.strokeWidth(strokeW)
              .strokeColor(c)
              .stroke();
    end
    return self;
end
function m.rectStroke(x, y, w, h, c, strokeW)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath()
              .rect(x, y, w, h)
              .strokeWidth(strokeW)
              .strokeColor(c)
              .stroke();
    end
    return self;
end

function m.ellipseFill(cx, cy, rx, ry, c)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath()
              .ellipse(cx, cy, rx, ry)
              .fillColor(c)
              .fill();
    end
    return self;
end

function m.ellipsesFill(ellipses, c)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath();
        for _, rc in ipairs(ellipses) do
            canvas.rect(rc.cx, rc.cy, rc.rx, rc.ry);
        end
        canvas.fillColor(c)
              .fill();
    end
    return self;
end
function m.ellipsesStroke(ellipses, c, strokeW)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath();
        for _, rc in ipairs(ellipses) do
            canvas.rect(rc.cx, rc.cy, rc.rx, rc.ry);
        end
        canvas.strokeWidth(strokeW)
              .strokeColor(c)
              .stroke();
    end
    return self;
end
function m.ellipseStroke(cx, cy, rx, ry, c, strokeW)
    local self = obj.new("RectStrokeDrawable")
    function self.draw(canvas)
        canvas.beginPath()
              .ellipse(cx, cy, rx, ry)
              .strokeWidth(strokeW)
              .strokeColor(c)
              .stroke();
    end
    return self;
end

function m.new()
    local self = obj.new("ComposeDrawable")
    function self.rect(x, y, w, h, round)

    end
    function self.ellipse(cx, cy, rx, ry)

    end
    function self.circle(cx, cy, r)

    end
    function self.line(sx, sy, ex, ey)

    end
    function self.fillColor(c)

    end
    function self.strokeColor(c, strokeW)

    end
    function self.fillGradient(g)

    end
    function self.strokeGradient(g, strokeW)

    end
    function self.draw(canvas)

    end
    return self;
end

return m