---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 上午 9:37
---
local g = require("fr.View")
local m = {}

function m.new(typeName)
    if( not typeName) then
        typeName = 'ViewGroup';
    end
    local super = g.new(typeName);
    local self = {};
    self.views = {};
    -- index from 0
    function self.addView(view, index) -- 0-> 1
        if(not index) then
            index = #self.views;
        end
        table.insert(self.views, index + 1, view);
        view.onAttach(self)
    end
    -- index from 0
    function self.removeView(view)
        local index;
        for i, v in ipairs(self.views) do
            if v == view then
                index = i;
                break;
            end
        end
        if(index) then
            table.remove(self.views, index)
            view.onDetach(self);
        end
    end
    function self.removeViewAt(index)
        local view = table.remove(self.views, index + 1)
        if(view) then
            view.onDetach(self);
        end
    end
    function self.setView(index, view)
        local old = self.views[index + 1];
        self.views[index + 1] = view;
        if(old) then
            old.onDetach(self)
        end
        view.onAttach(self);
    end
    -- index from 0
    function self.getChildAt(index)
        return self.views[index + 1];
    end
    function self.getChildrenCount()
        return #self.views;
    end
    function self.getParent()
        return super.parent;
    end
    function self.onInitialize(ctx)
        super.onInitialize(ctx);
        for _, v in ipairs(self.views) do
            v.onInitialize(ctx);
        end
    end
    function self.onDestroy()
        super.onDestroy();
        for _, v in ipairs(self.views) do
            v.onDestroy();
        end
    end
    function self.onDraw(canvas)
        super.onDraw(canvas);
        for _, v in ipairs(self.views) do
            v.onDraw(canvas);
        end
    end
end

return m;