---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/7 0007 上午 9:37
---
local g = require("fr.View")
local m = {}

function m.new(parent)
    local super = g.new(parent);
    local self = {};
    self.views = {};
    -- index from 0
    function self.addView(view, index) -- 0-> 1
        if(not index) then
            index = #self.views;
        end
        table.insert(self.views, index + 1, view);
    end
    -- index from 0
    function self.removeView(view)
        local index;
        for i, v in ipairs(self.views) do
            if v == view then
                index = i;
                break;
            end
        end
        table.remove(self.views, index)
    end
    function self.removeViewAt(index)
        table.remove(self.views, index + 1)
    end
    function self.setView(index, view)
        self.views[index + 1] = view;
    end
    -- index from 0
    function self.getChildAt(index)
        return self.views[index + 1];
    end
    function self.getChildrenCount()
        return #self.views;
    end
    function self.getParent()
        return super.parent;
    end
    function self.onInitialize()
        super.onInitialize();
        for _, v in ipairs(self.views) do
            v.onInitialize();
        end
    end
    function self.onDestroy()
        super.onDestroy();
        for _, v in ipairs(self.views) do
            v.onDestroy();
        end
    end
    function self.onDraw(canvas)
        super.onDraw(canvas);
        for _, v in ipairs(self.views) do
            v.onDraw(canvas);
        end
    end
end

return m;