---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/1 0001 下午 10:50
---

local m = {}

function m.new(parent)
    local self = {};
    self.parent = parent;

    function self.getParent()
        return self.parent;
    end

    function self.onInitialize()

    end

    function self.onDestroy()

    end

    function self.onDraw(canvas)

    end
    return self;
end

return m;