---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/12 0012 下午 5:43
---
local m = {}

m.PI = 3.14159265358979323846264338327;

function m.toRadian(angle)
    return angle * (m.PI / 180);
end

function m.toAngle(radian)
    return radian * (180 / m.PI);
end

return m;