---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/1 0001 下午 10:40
---
local m = {}

--config: renderType, renderState
function m.new(config)
    local self = {};
    self.views = {};

    function self.addView(view, index)
        if(not index) then
            index = #self.views;
        end
        table.insert(self.views, index, view);
    end

    return self;
end

return m;