---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/5 0005 下午 11:33
---

local m = {};

-- HorizontalAlign
m.Left   = 1;
m.Center = 2;
m.Right  = 4;
-- VerticalAlign
m.Top        = 8;
m.Middle     = 16;
m.Bottom     = 32;
m.Baseline   = 64;

return m;