---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/1 0001 下午 10:50
---

local m = {}

function m.new(parent)
    local self = {};

    function self.onCreate()

    end

    function self.onDestroy()

    end

    function self.onBackToFront()

    end

    function self.onFrontToBack()

    end

    function self.onDraw(canvas)

    end
    self.onCreate();
--[[    local meta = {
        __gc = function(t)
        end
    }
    setmetatable()]]
    return self;
end

return m;