---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/1 0001 下午 10:50
---

local m = {}

function m.new(parent)
    local self = {};

    function self.onInitialize()

    end

    function self.onDestroy()

    end

    function self.onDraw(canvas)

    end
    function self.equals(othView)

    end
    return self;
end

return m;